pipeline {
   agent any
    environment{
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
   stages {
        stage('destroy') {
            steps {
                sh 'terraform destroy -var-file="dev.tfvars" -auto-approve'
            }
        }
        stage('init') {
            steps {
                sh 'terraform init -var-file="dev.tfvars"'
            }
        }
        stage('apply') {
            steps {
              sh  'terraform apply -var-file="dev.tfvars" -auto-approve'
            }
        }
    }
}
